### Phat Doan

In [16]:
import pandas as pd

In [17]:
dev_df     = pd.read_csv('dataset/BC7-LitCovid-Dev.csv', sep=',')
test_gs_df = pd.read_csv('dataset/BC7-LitCovid-Test-GS.csv', sep=',')
test_df    = pd.read_csv('dataset/BC7-LitCovid-Test.csv', sep=',')
train_df   = pd.read_csv('dataset/BC7-LitCovid-Train.csv', sep=',')

In [18]:
dev_df

,pmid,journal,title,abstract,keywords,pub_type,authors,doi,label
0,32653511,Free Radic Biol Med,Potential benefits and risks of omega-3 fatty ...,"Studies have shown that infection, excessive c...",dha;epa;inflammation;oxidative stress;sars-cov...,"Journal Article;Research Support, Non-U.S. Gov...","Rogero, Marcelo M;Leao, Matheus de C;Santana, ...",10.1016/j.freeradbiomed.2020.07.005,Treatment
1,32427104,JMIR Public Health Surveill,Modeling COVID-19 Latent Prevalence to Assess ...,BACKGROUND: Emergence of the coronavirus disea...,covid-19;sir model;detection probability;forec...,Journal Article,"Turk, Philip J;Chou, Shih-Hsiung;Kowalkowski, ...",10.2196/19353,Prevention;Epidemic Forecasting
2,32605414,Int J Health Serv,The U.S. Health Care System on the Eve of the ...,Four decades of neoliberal health policies hav...,covid-19;united states;health care;health ineq...,Journal Article,"Himmelstein, David U;Woolhandler, Steffie",10.1177/0020731420937631,Prevention
3,33066278,Molecules,High-Throughput Screening for Inhibitors of th...,The global SARS-CoV-2 pandemic started late 20...,3clpro;covid-19;sars-cov-2;apomorphine;aporphi...,Journal Article,"Brown, Alistair S;Ackerley, David F;Calcott, M...",10.3390/molecules25204666,Treatment;Mechanism
4,32303609,Gut,COVID-19 and immunomodulation in IBD.,The current coronavirus pandemic is an ongoing...,cytokines;inflammation;inflammatory bowel disease,Journal Article;Review,"Neurath, Markus F",10.1136/gutjnl-2020-321269,Treatment;Mechanism
...,...,...,...,...,...,...,...,...,...
6234,32304387,Acad Med,Pandemics and Their Impact on Medical Training...,The ongoing coronavirus disease 2019 (COVID-19...,NaN,Journal Article,"Liang, Zhen Chang;Ooi, Shirley Beng Suat;Wang,...",10.1097/ACM.0000000000003441,Prevention
6235,32725795,Transbound Emerg Dis,Bats and humans during the SARS-CoV-2 outbreak...,The novel SARS-CoV-2 coronavirus has attracted...,covid-19;cov;one health;conservation;emerging ...,Journal Article,"Colunga-Salas, Pablo;Hernandez-Canchola, Giovani",10.1111/tbed.13751,Mechanism;Transmission
6236,32872009,Medicine (Baltimore),Pediatric massage therapy for restoring pediat...,BACKGROUND: The novel coronavirus disease 2019...,NaN,Journal Article,"Zhou, Ke-Lin;Dong, Shuo;Wang, Kang;Fu, Guo-Bin...",10.1097/MD.0000000000021581,Treatment
6237,32513808,Cleve Clin J Med,Procedural sedation in the COVID-19 era.,Resuming procedural sedation services for elec...,NaN,Journal Article,"Fawley, Nicholas;Abdelmalak, Basem",10.3949/ccjm.87a.ccc043,Prevention
6238,32781167,Anaesth Crit Care Pain Med,Haemodynamic monitoring and management in COVI...,PURPOSE: To survey haemodynamic monitoring and...,acute circulatory failure;covid-19;echocardiog...,Journal Article,"Michard, Frederic;Malbrain, Manu Lng;Martin, G...",10.1016/j.accpm.2020.08.001,Diagnosis;Treatment

In [19]:
dev_df.isnull().sum()

pmid           0
journal        0
title          0
abstract       0
keywords    1485
pub_type       0
authors       27
doi          139
label          0
dtype: int64

In [20]:
test_gs_df.isnull().sum()

pmid          0
journal       0
title         0
abstract     11
keywords    444
pub_type      0
authors       1
doi          26
label         0
dtype: int64

In [21]:
train_df.isnull().sum()

pmid           0
journal        0
title          0
abstract       0
keywords    5992
pub_type       0
authors      101
doi          554
label          0
dtype: int64

In [22]:
test_df.isnull().sum()

pmid          0
journal       0
title         0
abstract     11
keywords    444
pub_type      0
authors       1
doi          26
dtype: int64

In [23]:
test_df[test_df['abstract'].isnull()]

,pmid,journal,title,abstract,keywords,pub_type,authors,doi
34,34219343,Liver Int,Management of liver disease in Italy after one...,NaN,covid19;hcc;sars-cov-2;cirrhosis;liver transplant,Journal Article,"Ponziani, Francesca Romana;Aghemo, Alessio;Cab...",10.1111/liv.14998
386,34289169,J Med Virol,Previous SARS-CoV-2 infection is linked to low...,NaN,NaN,Letter,"Sprengholz, Philipp;Betsch, Cornelia",10.1002/jmv.27221
391,34216737,Int J Infect Dis,Evaluation of potassium peroxymonosulfate (MPS...,NaN,NaN,Journal Article,"Tulalamba, W;Assawamakin, A;Thayananuphat, A;V...",10.1016/j.ijid.2021.06.057
690,34132389,Br J Haematol,Primary haemophagocytic lymphohistiocytosis (C...,NaN,chediak-higashi;sars-cov-2;infant;primary hlh,Letter,"Lange, Matthias;Linden, Tobias;Muller, Hermann...",10.1111/bjh.17669
897,34213779,J Med Virol,Derangements of biochemical markers and thyroi...,NaN,NaN,Letter,"Asghar, Muhammad Sohaib;Yasmin, Farah;Dapke, K...",10.1002/jmv.27174
1100,34228876,Acta Physiol (Oxf),Relation between ORF8a and the mitochondrial p...,NaN,NaN,Editorial,"Zandi, Milad;Soltani, Saber",10.1111/apha.13712
1518,34351690,Acta Physiol (Oxf),How to increase cellular oxygen availability i...,NaN,NaN,Editorial,"Kulow, Vera A;Fahling, Michael",10.1111/apha.13724
1682,34212494,Am J Transplant,SARS-CoV-2 vaccine effectiveness trumps immuno...,NaN,clinical research/practice;health services and...,Letter,"Mossad, Sherif B",10.1111/ajt.16744
2157,34214257,Am J Transplant,Organ transplantation from deceased donors wit...,NaN,autoantibody;clinical research/practice;coagul...,Letter,"Greenhall, George H B;Ushiro-Lumb, Ines;Pavord...",10.1111/ajt.16735
2311,34229112,Rev Psiquiatr Salud Ment,Transient drop in the neutrophil count during ...,NaN,NaN,Case Reports,"Vallecillo, Gabriel;Marti-Bonany, Josep;Robles...",10.1016/j.rpsm.2021.06.002
2473,33785206,Am J Surg,Inaccurate nasopharyngeal testing in a patient...,NaN,NaN,Editorial,"Ramaraj, Akila B;Rice-Townsend, Samuel E",10.1016/j.amjsurg.2021.02.033

In [24]:
# Filling any NaNs with empty string ''

test_gs_df.fillna('', inplace=True)
train_df.fillna('', inplace=True)
dev_df.fillna('', inplace=True)

print(test_gs_df.isnull().sum(), '\n')
print(train_df.isnull().sum(), '\n')
print(dev_df.isnull().sum())

pmid        0
journal     0
title       0
abstract    0
keywords    0
pub_type    0
authors     0
doi         0
label       0
dtype: int64

pmid        0
journal     0
title       0
abstract    0
keywords    0
pub_type    0
authors     0
doi         0
label       0
dtype: int64

pmid        0
journal     0
title       0
abstract    0
keywords    0
pub_type    0
authors     0
doi         0
label       0
dtype: int64

In [25]:
# Dropping pmid, doi, journal, pub_type and authors columns

test_gs_df.drop(columns=['pmid', 'doi', 'journal', 'pub_type', 'authors'], inplace=True)
train_df.drop(columns=['pmid', 'doi', 'journal', 'pub_type', 'authors'], inplace=True)
dev_df.drop(columns=['pmid', 'doi', 'journal', 'pub_type', 'authors'], inplace=True)

In [26]:
# Concatenating all column features into one column
# Adding a [CLS] token at the start of each row
# Adding a [SEP] token between each column concats

train_df['features'] = ('[CLS] ' + train_df['title'].astype(str) + 
                        '[SEP] ' + train_df['keywords'].astype(str) + 
                        '[SEP] ' + train_df['abstract'].astype(str))
train_df = train_df[['features', 'label']]
print(train_df)

test_gs_df['features'] = ('[CLS] ' + test_gs_df['title'].astype(str) + 
                        '[SEP] ' + test_gs_df['keywords'].astype(str) + 
                        '[SEP] ' + test_gs_df['abstract'].astype(str))
test_gs_df = test_gs_df[['features', 'label']]
print(test_df)

dev_df['features'] = ('[CLS] ' + dev_df['title'].astype(str) + 
                        '[SEP] ' + dev_df['keywords'].astype(str) + 
                        '[SEP] ' + dev_df['abstract'].astype(str))
dev_df = dev_df[['features', 'label']]
print(dev_df)

                                                features                 label
0      [CLS] Potential role for tissue factor in the ...   Treatment;Mechanism
1      [CLS] Dietary therapy and herbal medicine for ...  Treatment;Prevention
2      [CLS] First report of manic-like symptoms in a...           Case Report
3      [CLS] Epidemiological Investigation of OHCWs w...            Prevention
4      [CLS] The impact of sofosbuvir/daclatasvir or ...             Treatment
...                                                  ...                   ...
24955  [CLS] Medical recommendations for home-confine...            Prevention
24956  [CLS] Determination of disease severity in COV...             Diagnosis
24957  [CLS] Baseline electrolyte abnormalities would...   Treatment;Diagnosis
24958  [CLS] COVID-19 in obstetrics 2020: the experie...            Prevention
24959  [CLS] Public Health Communication in Time of C...            Prevention

[24960 rows x 2 columns]
          pmid                journal  \
0     34336157          J Healthc Eng
1     34211701               F1000Res
2     34367415  Int J Clin Exp Pathol
3     34218393         Clin Rheumatol
4     34131026              CMAJ Open
...        ...                    ...
2495  34291555            Chembiochem
2496  34204119             J Clin Med
2497  34228511        JCO Oncol Pract
2498  34226900                 EJHaem
2499  34218774         Curr Pharm Des

                                                  title  \
0     Disentangling the Association of Hydroxychloro...
1     Risk factors for mortality in hospitalized pat...
2     Inflammation in COVID-19: from pathogenesis to...
3     Antimalarial drugs-are they beneficial in rheu...
4     Integration of virtual physician visits into a...
...                                                 ...
2495  Enzymatic Assays to Explore Viral mRNA Capping...
2496  Usefulness of Respiratory Mechanics and Labora...
2497  Descriptive Comparative Analysis of Patients W...
2498         Lessons learnt from COVID-19 coagulopathy.
2499  Nanotechnology-Based Approaches and Investigat...

                                               abstract  \
0     The efficacy of hydroxychloroquine (HCQ) in tr...
1     BACKGROUND: Peru was one of the countries with...
2     The coronavirus disease 2019 (COVID-19) was de...
3     The majority of the medical fraternity is cont...
4     BACKGROUND: British Columbia, like many jurisd...
...                                                 ...
2495  In eukaryotes, mRNA is modified by the additio...
2496  Whether a patient with severe coronavirus dise...
2497  PURPOSE: COVID-19 cancer patients (C19-CP) rep...
2498  The coronavirus disease 2019 (COVID-19) pandem...
2499  Severe acute respiratory syndrome coronavirus ...

                                               keywords  \
0                                                   NaN
1     adults;covid-19;latin america.;mortality;sars-...
2     covid-19;sars-cov-2;cytokine storm;inflammatio...
3     antimalarial drugs;covid-19;rheumatic diseases...
4                                                   NaN
...                                                 ...
2495  antiviral agents;high-throughput screening;mrn...
2496  covid-19;mechanical ventilation;respiratory fa...
2497                                                NaN
2498  covid-19;d-dimer;coagulopathy;fibrinogen;plate...
2499  covid-19;sars-cov-2;antiviral drugs;nanotechno...

                                              pub_type  \
0                                      Journal Article
1     Journal Article;Research Support, Non-U.S. Gov't
2                               Journal Article;Review
3                               Journal Article;Review
4                                      Journal Article
...                                                ...
2495                            Journal Article;Review
2496                                   Journal Article
2497                                   Journal Article
2498                            Journal Article;Review
2499                                   Journal Article

                                                authors  \
0     Di Castelnuovo, Augusto;Gialluisi, Alessandro;...
1     Diaz-Velez, Cristian;Urrunaga-Pastor, Diego;Ro...
2                                     Wong, Rebecca S Y
3                                Grygiel-Gorniak, Bogna
4     Ho, Kendall;Lauscher, Helen Novak;Stewart, Kur...
...                                                 ...
2495                  Kasprzyk, Renata;Jemielity, Jacek
2496  Kasugai, Daisuke;Ozaki, Masayuki;Nishida, Kazu...
2497  Mariniello, Annapaola;Bironzo, Paolo;Pisano, C...
2498                                     Thachil, Jecko
2499  Rahman, Md Mominur;Ahmed, Muniruddin;Islam, Mo...

                                    doi
0                  10.1155/2021/5556207
1        10.12688/f1000research.51474.1
2                                   NaN
3            10.1007/s10067-021-05805-5
4                10.9778/cmajo.20200265
...                                 ...
2495             10.1002/cbic.202100291
2496                10.3390/jcm10112513
2497                10.1200/OP.21.00098
2498                   10.1002/jha2.228
2499  10.2174/1381612827666210701150315

[2500 rows x 8 columns]
                                               features  \
0     [CLS] Potential benefits and risks of omega-3 ...
1     [CLS] Modeling COVID-19 Latent Prevalence to A...
2     [CLS] The U.S. Health Care System on the Eve o...
3     [CLS] High-Throughput Screening for Inhibitors...
4     [CLS] COVID-19 and immunomodulation in IBD.[SE...
...                                                 ...
6234  [CLS] Pandemics and Their Impact on Medical Tr...
6235  [CLS] Bats and humans during the SARS-CoV-2 ou...
6236  [CLS] Pediatric massage therapy for restoring ...
6237  [CLS] Procedural sedation in the COVID-19 era....
6238  [CLS] Haemodynamic monitoring and management i...

                                label
0                           Treatment
1     Prevention;Epidemic Forecasting
2                          Prevention
3                 Treatment;Mechanism
4                 Treatment;Mechanism
...                               ...
6234                       Prevention
6235           Mechanism;Transmission
6236                        Treatment
6237                       Prevention
6238              Diagnosis;Treatment

[6239 rows x 2 columns]

In [27]:
test_gs_df.to_csv('dataset/cleaned/test_df.csv', sep=',')
train_df.to_csv('dataset/cleaned/train_df.csv', sep=',')
dev_df.to_csv('dataset/cleaned/validate_df.csv', sep=',')

In [28]:
print(len(train_df))

24960

In [30]:
train_df = train_df.sample(n=10000, random_state=42, replace=False)
test_gs_df = test_gs_df.sample(n=2000, random_state=42, replace=False)

test_gs_df.to_csv('dataset/cleaned/mini_test_df.csv', sep=',')
train_df.to_csv('dataset/cleaned/mini_train_df.csv', sep=',')